
# number of QMC startup trials to run before the TPE algorithm
n_startup_trials: 128

name_startup_sampler: qmc
name: tpe

cfg:
  _target_: optuna.samplers.TPESampler
  # The random sampling is used instead of the TPE algorithm until the given number of trials finish in the same study.
  n_startup_trials: 0
  multivariate: true
  group: true
  seed: ${seed}
  warn_independent_sampling: false
  
  
# https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.QMCSampler.html 

# Quasi Monte Carlo (QMC) sequences are designed to have lower discrepancies than standard random sequences. 
# They are known to perform better than the standard random sequences in hyperparameter optimization.

cfg_startup:
  _target_: optuna.samplers.QMCSampler
  # can be "sobol" or "halton"
  # -> if using sobol, it is recommended that the number of trials should be set as power of two.
  qmc_type: sobol
  # Scrambling is capable of producing better Sobol sequences.
  scramble: true
  # seed for the RNG
  seed: ${seed}
  warn_independent_sampling: false



