cfg:
  _target_: models.preset.hn_ptgru
  hidden_features: 768
  num_blocks: 6
  token_dim: 384
  pe_dropout_p: 0.0
  block_norm: BatchNorm1d
  block_act_fn: ReLU
  block_dropout_p: 0.0

name: hn_ptgru