cfg:
  _target_: models.preset.tfm
  pe_type: absolute
  hidden_features: 256
  num_blocks: 6
  num_heads: 8
  mlp_factor: 4.0
  pooling_type: cls
  last_activation: ReLU
  pe_dropout_p: 0.0
  block_activation: relu
  block_dropout_p: 0.0

name: tfm