### PresetHelper settings

# synthesizer used to generate the dataset
name: diva

# synthesizer parameters to exclude when generating presets (support asterisk for excluding a group of parameters)
parameters_to_exclude_str: 
  - "main:output"
  - "vcc:*"
  - "opt:*"
  - "scope1:*"
  - "clk:*"
  - "arp:*"
  - "plate1:*"
  - "delay1:*"
  - "chrs2:*"
  - "phase2:*"
  - "rtary2:*"
  - "*keyfollow"
  - "*velocity"
  - "env1:model"
  - "env2:model"
  - "*trigger"
  - "*release_on"
  - "env1:quantise"
  - "env2:quantise"
  - "env1:curve"
  - "env2:curve"
  - "lfo1:sync"
  - "lfo2:sync"
  - "lfo1:restart"
  - "lfo2:restart"
  - "mod:rectifysource"
  - "mod:invertsource"
  - "mod:addsource*"
  - "*revision"
  - "vca:pan"
  - "vca:volume"
  - "vca:vca"
  - "vca:panmodulation"
  - "vca:panmoddepth"
  - "vca:mode"
  - "vca:offset"