# @package _global_

defaults:
  - train
  - _self_
  # - synth: ???
  # - settings: default
  # - loss_sch: ???

callbacks: null

# ckpt to the model to evaluate
train_ckpt: diva_ssm_mn20_hc_v1_loss_a_test.ckpt

# batch size to compute the test metrics
batch_size: 32

# number of batch to export
batch_to_export: 4


# other configs
path_to_train_ckpt: ${paths.root_dir}/checkpoints/${train_ckpt}


hydra:
  run:
    dir: ${paths.root_dir}/logs/ssm/eval_${task_name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir:  ${paths.root_dir}/logs/ssm/eval_multirun_${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${task_name}

wandb: 
  project: synth_proxy_ssm_eval