# @package _global_

defaults:
  - _self_
  - synth: diva
  - settings: default
  - loss_sch: ???

# see synth configs for synth specific HPs and configs

######################################
############ Main Configs ############
######################################

# tag to identify the run
tag: ???

#dataset to use for finetuning
dataset_name: mn20_hc_v1

# batch size for the train and val dataloaders
batch_size: 64

# scaling factor for the cat loss (in parameter loss)
# since way bigger than the rest
lw_cat: 0.01

# number of epochs
trainer:
  max_epochs: 250
  log_every_n_steps: 50
  deterministic: True
  accelerator: gpu
  devices: 1
  default_root_dir: ${paths.output_dir}

# for resuming tranining
ckpt_path: null

##########################################
############ Lightning Module ############
##########################################
optimizer:
  scheduler_kwargs:
    factor: 0.5
    patience: 10

wandb_watch_args:
  log: null
  log_freq: 100 