# mix parameter loss into audio embedding loss
param:
  start: ${start}
  warm: ${warm}
  start_value: 0.0
  end_value: 0.5

perc:  
  start: ${start}
  warm: ${warm}
  start_value: 1.0
  end_value: 5.0

name: mix_p_a