# mix audio embedding loss into parameter loss
param:
  start: ${start}
  warm: ${warm}
  start_value: 1.0
  end_value: 0.5

perc:  
  start: ${start}
  warm: ${warm}
  start_value: 0.0
  end_value: ${mul:0.5,${lw_a}}

name: mix_a_p