# mix parameter loss into audio embedding loss
param:
  start: ${start}
  warm: ${warm}
  start_value: 0.0
  end_value: 0.5

perc:  
  start: ${start}
  warm: ${warm}
  start_value: ${mul:1.0,${lw_a}}
  end_value: ${mul:0.5,${lw_a}}

name: mix_p_a