# @package _global_

# synthesizer to use
synth: diva

# path to the checkpoint to load for the synth proxy
path_to_ckpt: ${paths.root_dir}/checkpoints/diva_tfm_mn20_mel_e59.ckpt

optimizer:
  optimizer_kwargs:
    lr: 3e-4 # todo: take from HPO
    betas:
      - 0.91 # todo: take from HPO
      - 0.98 # todo: take from HPO
    eps: 1e-7 # todo: take from HPO
    weight_decay: 0.3 # todo: take from HPO
  num_warmup_steps: 1080 # todo: take from HPO

label_smoothing: 0.01 # todo: take from HPO

# dexed: len(train_dataset) is 22116

# step number at which the linear schedule start for both loss
# total_num_steps = num_epochs * dataset_size // batch_size
# to follow SSSSM-DDSP paper, should be num_steps // 8
# for dexed we have: 400 * 22116 // 64 = 138225; 138225 // 8 = 17278
start: 17278

# how long should the linear schedule last
# to follow SSSSM-DDSP paper, should be num_steps // 2 - start
warm: 51834