# @package _global_

# synthesizer to use
synth: dexed

# path to the checkpoint to load for the synth proxy
path_to_ckpt: ${paths.root_dir}/checkpoints/dexed_tfm_mn20_hc_v1_ft_e230_loss0.0201.ckpt

optimizer:
  optimizer_kwargs:
    lr: 7e-3
    betas:
      - 0.86
      - 0.98
    eps: 1e-8
    weight_decay: 0.01
  num_warmup_steps: 2070 # 6 epochs

label_smoothing: 0.02

# dexed: len(train_dataset) is 22116

# step number at which the linear schedule start for both loss
# total_num_steps = num_epochs * dataset_size // batch_size
# to follow SSSSM-DDSP paper, should be num_steps // 8
# for dexed we have: 400 * 22116 // 64 = 138225; 138225 // 8 = 17278
start: 17278

# how long should the linear schedule last
# to follow SSSSM-DDSP paper, should be num_steps // 2 - start
warm: 51834