# @package _global_

# synthesizer to use
synth: diva

# path to the checkpoint to load for the synth proxy
path_to_ckpt: ${paths.root_dir}/checkpoints/diva_tfm_mn20_hc_v1_ft_e50_loss0.0379.ckpt

optimizer:
  optimizer_kwargs:
    lr: 3e-4
    betas:
      - 0.91
      - 0.98
    eps: 1e-7
    weight_decay: 0.3
  num_warmup_steps: 1080

label_smoothing: 0.01

# diva: len(train_dataset)= 7721 if [0.8, 0.1, 0.1] split is used

# step number at which the linear schedule start for both loss
# total_num_steps = num_epochs * dataset_size // batch_size
# to follow SSSSM-DDSP paper, should be num_steps // 8
# for diva we have: 400 * 7721 // 64 = 48256; 48256 // 8 = 6032
start: 6032

# how long should the linear schedule last
# to follow SSSSM-DDSP paper, should be num_steps // 2 - start
warm: 18096